apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: Flux-apps
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/beertwanger/Flux-apps
